### ISSUE TITLE
[feature request] Cached Generator

### ISSUE THREAD

**Issue by GDmac** [pmjones/AutoRoute#12]
Since generating links to other parts of the application is very common, 
i am wondering if a (file) caching Generator class would be beneficial. 

it could probably prevent loading multiple controller files,
and prevent/speed-up (multiple) reflections / reversers for controllers.
(imagine a page with links to blogs, articles, media, archives, categories, etc.)

general ideas:
- store an array-mapping of class/params based on controller-filemtime
- add automated (cli/composer-generated) mapping-cache into git (generate on dev, commit, push, deploy)

**Comment by pmjones** [comment]
I tried out some caching ideas in pre-release trials of the 2.0 series, and I found no noticeable speedup. However, if you want to put together an implementation with speed comparisons, I'd be interested to look it!

**Comment by GDmac** [comment]
i have a setup (work in progress) that extends, generator (cachedGenerator), actions and action 
and it has to provide and cache methods (method, parameters, type) that action expects from reflection.
The main idea is to read in one array with info, instead of include all controller-classes for reflection.

I have a basic test menu structure setup, 
but you can imagine many more url/links on the page, to many parts of application.
Each would include the files and reflection for every controller
```php
        // menu structure
        $menu = [
            'home' => $generator->generate(self::class),
            'articles' => $generator->generate(GetArticles::class),
            'photos' => $generator->generate(GetPhotos::class),
            'article-categories' => [],
            'photo-categories' => [],
            'some' => $generator->generate(GetPagesPage::class, 22),
            'more' => $generator->generate(GetPagesPage::class, 33),
            'pages' => $generator->generate(GetPagesPage::class, 44),
        ];
        foreach(range(1, 20) as $number) {
            // article- and photo- categories
            $catname = "cat{$number}";
            $menu['article-categories'][$catname] = $generator->generate(GetArticlesCategory::class, $number);
            $menu['photo-categories'][$catname] = $generator->generate(GetPhotosCategory::class, $number);
        }

        $pageVars = [
            'main-article-link' => $generator->generate(GetArticlesArticle::class, 101),
            'popular-articles' => [],
            'latest-photos' => [],
            'latest-comments' => [],
        ];
        foreach(range(1, 5) as $number) {
            $name = "name{$number}";
            $pageVars['popular-articles'][$name] = $generator->generate(GetArticlesArticle::class, $number);
            $pageVars['latest-photos'][$name] = $generator->generate(GetPhotosPhoto::class, $number);
            $pageVars['latest-comments'][$name] = $generator->generate(GetCommentsComment::class, $number);
        }
```
