### ISSUE TITLE
Great!

### ISSUE THREAD

**Issue by cxj** [pmjones/AutoRoute#4]
This is really slick.  Any chance you'd integrate into Radar.Adr?  :-)

**Comment by harikt** [comment]
Wow ... Just noticed this and look very similar to what we currently use for routing and action class.

As always nice work Paul.

**Comment by pmjones** [comment]
You guys are awesome. :-)

@cxj I don't anticipate doing so. However, it *is* going to be integrated into something else, though I don't have a release timeframe for it.

@harikt Great minds think alike!
