### ISSUE TITLE
Do you plan on supporting Windows OS systems?

### ISSUE THREAD

**Issue by TheTechsTech** [pmjones/AutoRoute#6]
I was initially getting failing builds, with "File not found" readouts. Updated the Dumper class method `getFiles()`. That no longer shows, but now getting:

```
1) AutoRoute\IgnoreTest::testDumper
TypeError: Argument 1 passed to AutoRoute\Actions::actionExists() must be of the type string, boolean given, called in AutoRoute\src\Actions.php on line 205

AutoRoute\src\Actions.php:166
AutoRoute\src\Actions.php:205
AutoRoute\src\Dumper.php:51
AutoRoute\src\Dumper.php:27
AutoRoute\tests\IgnoreTest.php:188

2) AutoRoute\SuffixTest::testDumper
TypeError: Argument 1 passed to AutoRoute\Actions::actionExists() must be of the type string, boolean given, called in AutoRoute\src\Actions.php on line 205

AutoRoute\src\Actions.php:166
AutoRoute\src\Actions.php:205
AutoRoute\src\Dumper.php:51
AutoRoute\src\Dumper.php:27
AutoRoute\tests\SuffixTest.php:186
```

**Comment by GDmac** [comment]
php automagically translates directory separators for file access, try to make use of that :-)

**Comment by TheTechsTech** [comment]
> php automagically translates directory separators for file access, try to make use of that :-)

What, I don't get what you mean? It has nothing to do with directory translation. `getFiles()` using an Linux shell `find` command to get directory listing, and the command does not work the same on Windows. I changed my fork to use PHP `glob` function instead. 

I wasn't asking for help, just wondering the direction of this project.

**Comment by pmjones** [comment]
Hey there @techno-express -- if you are still interested, can you try out #10 and see if that solves your problem? (If you don't have time or inclination, no big deal, and thanks for your patience.)

**Comment by TheTechsTech** [comment]
Yes, that works too, thanks.
